name: NPM Package
on:
  push:
    branches-ignore:
      - "**"
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        description: "Package version"
        required: true
      tag:
        description: "Package tag"
        required: true
        default: "latest"
        type: choice
        options:
          - latest
          - beta

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  npm-upload:
    name: NPM Package Build and Upload
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - id: semver
        run: |
          SEMVER="${{ github.event.inputs.version }}"
          if [ -z "$SEMVER" ]; then
            # No manual input, we must be running on a tag
            SEMVER="${GITHUB_REF/refs\/tags\/v/}"
          fi
          echo "semver=${SEMVER}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Set Version
        run: npm version --no-git-tag-version "${{ steps.semver.outputs.semver }}"

      - name: Build
        run: npm run build

      - name: Publish
        run: |
          RELEASE_TAG="${{ github.event.inputs.tag }}"
          if [ -z "$RELEASE_TAG" ]; then
            if echo "${{ steps.semver.outputs.semver }}" | grep -q -- '-beta'; then
              RELEASE_TAG=beta
            else
              RELEASE_TAG=latest
            fi
          fi
          npm publish --tag "$RELEASE_TAG" --access public
