name: ethereum-store package tests
on: [push]

env:
  CI: "true"

jobs:
  tests:
    name: ethereum-store package tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm run test -- --coverage
